name = "FTB GO BRRR"
author = "ImUrX"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "92ab0263e553987ab0676382d1c3a8e4365d1c177fca008ce79f7b363f61350c"

[versions]
forge = "47.2.21"
minecraft = "1.20.1"
