name = "FTB GO BRRR"
author = "ImUrX"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "073b3ec35b8b12be78f849b369552c25d748e832a28d0ff845d08d89bcd34423"

[versions]
forge = "47.2.21"
minecraft = "1.20.1"
