name = "FTB GO BRRR"
author = "ImUrX"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "29241a1f590684124f3091cd90ea7562cfb22ff8253852cf05d959be15f3bf2d"

[versions]
forge = "47.2.21"
minecraft = "1.20.1"
