name = "FTB GO BRRR"
author = "ImUrX"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "debd19170261b90b4bf46d5406bfa4fd744066a02688c6f574091d7e6d47f29e"

[versions]
forge = "47.2.21"
minecraft = "1.20.1"
